-- MySQL Script generated by MySQL Workbench
-- Wed May 31 11:03:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE IF NOT EXISTS `allo-cocktail` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `allo-cocktail`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema allo_cocktail_bdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema allo_cocktail_bdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `allo_cocktail_bdd` DEFAULT CHARACTER SET utf8 ;
USE `allo_cocktail_bdd` ;

-- -----------------------------------------------------
-- Table `allo_cocktail_bdd`.`cocktail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `allo_cocktail_bdd`.`cocktail` (
  `id_cocktail` INT(11) NOT NULL,
  `nameCocktail` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `quantity` INT(11) NOT NULL,
  PRIMARY KEY (`id_cocktail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_UNIQUE` ON `allo_cocktail_bdd`.`cocktail` (`id_cocktail` ASC);


-- -----------------------------------------------------
-- Table `allo_cocktail_bdd`.`accompagnement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `allo_cocktail_bdd`.`accompagnement` (
  `id_accompagnement` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT(11) NOT NULL DEFAULT 0,
  `price` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_accompagnement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_accompagnement_UNIQUE` ON `allo_cocktail_bdd`.`accompagnement` (`id_accompagnement` ASC);


-- -----------------------------------------------------
-- Table `allo_cocktail_bdd`.`bar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `allo_cocktail_bdd`.`bar` (
  `idbar` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `addresse` VARCHAR(45) NOT NULL,
  `_id_cocktail` INT(11) NOT NULL,
  `_id_accompagnement` INT(11) NOT NULL,
  PRIMARY KEY (`idbar`),
  CONSTRAINT `id_cocktail`
    FOREIGN KEY (`_id_cocktail`)
    REFERENCES `allo_cocktail_bdd`.`cocktail` (`id_cocktail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_accompagnement`
    FOREIGN KEY (`_id_accompagnement`)
    REFERENCES `allo_cocktail_bdd`.`accompagnement` (`id_accompagnement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idbar_UNIQUE` ON `allo_cocktail_bdd`.`bar` (`idbar` ASC);

CREATE UNIQUE INDEX `id_cocktail_UNIQUE` ON `allo_cocktail_bdd`.`bar` (`_id_cocktail` ASC);

CREATE UNIQUE INDEX `_id_accompagnement_UNIQUE` ON `allo_cocktail_bdd`.`bar` (`_id_accompagnement` ASC);


-- -----------------------------------------------------
-- Table `allo_cocktail_bdd`.`package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `allo_cocktail_bdd`.`package` (
  `id_package` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  `_id_cocktail` INT(11) NOT NULL,
  `_id_accompagnement` INT(11) NOT NULL,
  PRIMARY KEY (`id_package`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `id_package_UNIQUE` ON `allo_cocktail_bdd`.`package` (`id_package` ASC);

CREATE UNIQUE INDEX `_id_cocktail_UNIQUE` ON `allo_cocktail_bdd`.`package` (`_id_cocktail` ASC);

CREATE UNIQUE INDEX `_id_accompagnement_UNIQUE` ON `allo_cocktail_bdd`.`package` (`_id_accompagnement` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
